$(document).ready(function(){
    $('#btn').click(function(){
    	//alert('hi');
       $('#div_content').load('tab.jsp');
    });
});
$(document).ready(function(){
    $('#btn1').click(function(){
    	//alert('hi');
       $('#div_content').load('form1.jsp');
    });
});